# Generated by Django 2.0.1 on 2018-03-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
