# Generated by Django 2.0.1 on 2018-03-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_login', '0002_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='internship1',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='internship2',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='internship3',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='internship4',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
